# @link https://tech-blog.rakus.co.jp/entry/20240208/issue_forms
name: 不具合報告
description: 不具合報告はこちら。
labels: ["不具合"]
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        不具合の概要を記載してください。
        見た目に関係する場合は、スクリーンショット等を貼り付けてください。
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: 再現環境
      description: |
        再現環境を記載してください。
        例：
        Chrome + Windows
        Edge + Windows
        Chrome + macOS
        Safari + macOS
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: 発生時刻
      description: |
        不具合が発生した日付と時刻を、可能な限り記載してください。
        ログとの照合を行うため、可能な限り、分単位で正しい時刻を記載してください。
  - type: textarea
    id: process
    attributes:
      label: 再現手順
      description: 不具合を再現させる手順を記載してください。
      value: |
        1.
        2.
        3.
  - type: textarea
    id: supplement
    attributes:
      label: 補足
