name: 改善提案
description: 改善提案はこちら。
labels: ["提案"]
body:
  - type: input
    id: version
    attributes:
      label: バージョン
      description: 現在のバージョンを記載してください（不明な場合は空欄でOK）。
      placeholder: "例: 1.2.0"
  - type: textarea
    id: background
    attributes:
      label: 背景
      description: どのような課題を抱えてissueを立てたのか、経緯や前提を記載してください。
    validations:
      required: true
  - type: textarea
    id: merit
    attributes:
      label: メリット
      description: 改善することでどのようなメリットがあるのかを記載してください。
    validations:
      required: true
  - type: textarea
    id: do
    attributes:
      label: やること
      description: このissueで取り組むより具体的な項目を記載してください。
      value: |
        -
        -
        -
  - type: textarea
    id: supplement
    attributes:
      label: 補足
